{% set name = "bw2speedups" %}
{% set version = "2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bw2speedups-{{ version }}.tar.gz
  sha256: a1c8b7505655f3a39e71e9db4138339b6245ace9c93e23519aeaa5f0af3cdef7

build:
  number: 1
  script:
    - {{ PYTHON }} setup.py build_ext -j{{ CPU_COUNT }}
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython
    - numpy
  host:
    - python
    - setuptools
    - numpy
    - cython
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - bw2speedups
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/brightway-lca/brightway2-speedups
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Cython functions to speed up Brightway2 LCA calculations
  description: 'A series of function written in Cython that speed up critical functions to improve the overall performance of the Brightway2 life cycle assessment framework.'

extra:
  recipe-maintainers:
    - cmutel
